# Generated by Django 4.2.16 on 2024-10-21 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_teacher_takes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takes',
            name='grade',
        ),
    ]
