# Generated by Django 4.2.16 on 2024-10-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_remove_takes_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='takes',
            name='grade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
