# Generated by Django 4.2.16 on 2024-10-21 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_takes_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='takes',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.teacher'),
            preserve_default=False,
        ),
    ]
